### ISSUE TITLE
helm/helm2 confusion

### ISSUE THREAD

**Issue by stuart23** [Azure/k8s-bake#19]
It seems that 'helm2' is valid as the renderEngine, and not 'helm': https://github.com/Azure/k8s-bake/blob/0df3471ef235b34dee2fdd1663896083116d6dd3/src/run.ts#L183

However the README has `renderEngine: 'helm'`. Should this be helm2?

**Comment by ds-ms** [comment]
It supports both. https://github.com/Azure/k8s-bake/blob/releases/v1/src/run.ts#L200

I guess I missed porting that change back to master. I'll do it; thanks for posting this :)

**Comment by stuart23** [comment]
@ds-ms thank you!
