### ISSUE TITLE
Problem with default working directory

### ISSUE THREAD

**Issue by jjindrich** [Azure/k8s-bake#40]
I have pipeline with job:

  deploy:
    name: 'Deploy to dev'
    runs-on: ubuntu-latest
    environment: dev    
    defaults:
      run:
        shell: bash
        working-directory: src-web

But the step is not using this working directory and I have to use direct ./src-web path
   - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: './src-web/charts/web'
        helm-version: 'latest'
        silent: 'false'
      id: bake

**Comment by jjindrich** [comment]
@shigupt202 can we work on this ?

**Comment by davidgamero** [comment]
hello, the `working-directory` option appears to only work for `run` steps based on the documentation, and doesn't override paths for `uses` steps that rely on external actions

https://github.community/t/use-working-directory-for-entire-job/16747
https://github.community/t/use-working-directory-for-entire-job/16747/2

**Comment by jjindrich** [comment]
I have this workflow, check it https://github.com/jjindrich/jjazure-web-dotnetcore/blob/master/.github/workflows/webapi-build-deploy.yml

As is in comment, working directory doesn't work for only this action, for other actions works.

**Comment by OliverMKing** [comment]
Hi! This is not a priority right now but we'd welcome any PRs.

**Comment by jjindrich** [comment]
> do you have an example of an action that uses the working-directory other than a `run` step?

Logically when are you referring file locations it makes sense to apply working directory.

**Comment by jjindrich** [comment]
@davidgamero any updates ?

**Comment by davidgamero** [comment]
> I have this workflow, check it https://github.com/jjindrich/jjazure-web-dotnetcore/blob/master/.github/workflows/webapi-build-deploy.yml
> 
> As is in comment, working directory doesn't work for only this action, for other actions works.

In this linked workflow, I don't see any steps using the `working-directory` input except `run` steps. The other actions used don't seem to have a `working-directory` input so it just skips those. If I missed one, please let me know and I'll take another look.

We would welcome a PR to add a new `working-directory` input for this action that would allow it to fit the use case it looks like you have, but it isn't on our current roadmap.
The PR development would have to be community-driven, but we are happy to review it.
@jjindrich
