### ISSUE TITLE
New release with helm namespace feature

### ISSUE THREAD

**Issue by armrib** [Azure/k8s-bake#56]
Hi, can you do a new release with helm namespace feature please ?
At the moment (March 22nd 2022) main doesn't work so I'll wait for the new release ;)

**Comment by armrib** [comment]
I tried with main and sha 6d27e77ac46a5c7fe2af0b876591a280fd137de7 but both give the same kind of result:

Run azure/k8s-bake@6d27e77ac46a5c7fe2af0b876591a280fd137de7
Error: File not found: '/home/runner/work/_actions/azure/k8s-bake/6d27e77ac46a5c7fe2af0b876591a280fd137de7/lib/run.js'

**Comment by OliverMKing** [comment]
I created a new release. v2.2 will work.
