### ISSUE TITLE
Feature Request: Migrate set-output command to Environment files

### ISSUE THREAD

**Issue by manhhavu** [Azure/k8s-bake#75]
### Feature request

Currently, while running k8s-bake, Github Actions is giving this warning

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Please consider to use environment files to make the warning disappear.

**Comment by OliverMKing** [comment]
Hi! Thanks for letting us know.

This has been fixed and should work in `v2.4` (and `v2`).
