### ISSUE TITLE
Deprecated NodeJs version

### ISSUE THREAD

**Issue by CristianAtMaersk** [Azure/k8s-bake#91]
In Github Actions I got the error using azure/k8s-bake@v2 task.

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/k8s-bake@v2`

Could you please update deprecated version?

**Comment by CristianAtMaersk** [comment]
https://github.com/Azure/k8s-bake/pull/90 solves this issue

**Comment by davidgamero** [comment]
new v3 release should resolve this, feel free to reopen if issue persists
